# Generated by Django 6.0 on 2026-05-20 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_alter_category_options_alter_category_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default=dict, verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default='2026-01-01', verbose_name='Дата доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('09:00-11:00', '09:00 - 11:00'), ('11:00-13:00', '11:00 - 13:00'), ('13:00-15:00', '13:00 - 15:00'), ('15:00-17:00', '15:00 - 17:00'), ('17:00-19:00', '17:00 - 19:00'), ('19:00-21:00', '19:00 - 21:00')], default='09:00-11:00', max_length=50, verbose_name='Время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
