# Generated by Django 6.0.4 on 2026-05-13 10:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_is_featured_alter_category_slug_delete_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSlugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(populate_from='title')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, populate_from='name', unique=True),
        ),
    ]
