# Generated by Django 6.0.4 on 2026-05-13 11:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_autoslugmodel_alter_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoSlugModel',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
