# Generated by Django 6.0 on 2026-05-13 16:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_autoslugmodel_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
