# Generated by Django 6.0.4 on 2026-05-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_category_id_product_category'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstructure',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderstructure',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderstructure',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderstructure',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalog.product'),
        ),
    ]
